let suggestions = [
    "Channel",
    "YouTube",
    "YouTuber",
    "YouTube Channel",
    "Blogger",
    "Hollywood",
    "Bollywood",
    "Vlogger",
    "Vechiles",
    "Facebook",
    "Freelancer",
    "Facebook Page",
    "Designer",
    "Developer",
    "Web Designer",
    "Web Developer",
    "How to learn HTML & CSS",
    "How to learn JavaScript",
    "How to become a Freelancer",
    "How to become a Web Designer",
    "How to start a Gaming Channel",
    "How to start a YouTube Channel",
    "What does HTML stands for?",
    "What does CSS stands for?",
    "Football",
    "American Football",
    "Cristiano Ronaldo",
    "Economy",
    "How to become rich",
    "Islam",
    "How to become Muslim",
    "what is the right religion ?",
    "Who is the prophet Muhammed",
    "Racism",
    "News",
    "Fire",
    "Video games",
    "Is playing video games harmful?",
    "Who am I ?",
    "Where am I",
    "What is pickatopic.com ?",
    "Who made pickatopic.com ?",
    "I'm bored",
    "I am bored",
    "Egypt",
    "English",
    "Arabic",
    "Spanish",
    "Russian",
    "Indian",
    "Latin",
    "Romainian",
    "Mexican",
    "Biology",
    "Chemistry",
    "Ecology",
    "Math",
    "Mathimatics",
    "Hestory",
    "Art",
    "Computer",
    "Computer Science",
    "Digital Technology",
    "Data Science",
    "Engineering",
    "Geometry",
    "Photos",
    "Windows",
    "Microsoft",
    "India",
    "Cairo",
    "Big Data",
    "Fonts",
    "Calligraphy",
];